apiVersion: v1
kind: Service
metadata:
  name: flask-quiz-service
spec:
  type: NodePort
  selector:
    app: flask-quiz
  ports:
  - port: 5001
    targetPort: 5001

    nodePort: 30085

